//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class carrito
    {
        public int productoId { get; set; }
        public int userId { get; set; }
        public int cantidad_producto { get; set; }
        public System.DateTime fecha_agregado { get; set; }
        public System.DateTime fecha_modificado { get; set; }
    }
}
