//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class promociones_productos
    {
        public int productoId { get; set; }
        public int promocionId { get; set; }
        public Nullable<System.DateTime> fecha_inicial_promocion { get; set; }
        public Nullable<System.DateTime> fecha_final_promocion { get; set; }
    
        public virtual productos productos { get; set; }
        public virtual promociones promociones { get; set; }
    }
}
