USE BDprogramacionV
GO
/*
delete from Pais;
delete from Provincia;
delete from Canton;
delete from Distrito;

DBCC CHECKIDENT ('[Pais]', RESEED, 0);
DBCC CHECKIDENT ('[Provincia]', RESEED, 0);
DBCC CHECKIDENT ('[Canton]', RESEED, 0);
DBCC CHECKIDENT ('[Distrito]', RESEED, 0);*/

insert into Pais values ('Costa Rica',2);
Insert into Provincia values('SAN JOSE', 1,2);
Insert into Canton values (1, 'SAN JOSE',2);
Insert into Distrito values (1, 1,'Carmen',2)
Insert into Distrito values (1, 1,'Merced',2)
Insert into Distrito values (1, 1,'Hospital',2)
Insert into Distrito values (1, 1,'Catedral',2)
Insert into Distrito values (1, 1,'Zapote',2)
Insert into Distrito values (1, 1,'San Francisco de Dos Ríos',2)
Insert into Distrito values (1, 1,'Uruca',2)
Insert into Distrito values (1, 1,'Mata Redonda',2)
Insert into Distrito values (1, 1,'Pavas',2)
Insert into Distrito values (1, 1,'Hatillo',2)
Insert into Distrito values (1, 1,'San Sebastián',2)
Insert into Canton values (1,'ESCAZU',2);
Insert into Distrito values (1,2,'Escazú',2)
Insert into Distrito values (1,2,'San Antonio',2)
Insert into Distrito values (1,2,'San Rafael',2)
Insert into Canton values (1,'DESAMPARADOS',2);
Insert into Distrito values (1,3,'Desamparados',2)
Insert into Distrito values (1,3,'San Miguel',2)
Insert into Distrito values (1,3,'San Juan de Dios',2)
Insert into Distrito values (1,3,'San Rafael Arriba',2)
Insert into Distrito values (1,3,'San Antonio',2)
Insert into Distrito values (1,3,'Frailes',2)
Insert into Distrito values (1,3,'Patarrá',2)
Insert into Distrito values (1,3,'San Cristóbal',2)
Insert into Distrito values (1,3,'Rosario',2)
Insert into Distrito values (1,3,'Damas',2)
Insert into Distrito values (1,3,'San Rafael Abajo',2)
Insert into Distrito values (1,3,'Gravilias',2)
Insert into Distrito values (1,3,'Los Guido',2)


Insert into Provincia values('HEREDIA', 1,2);
Insert into Canton values (2,' HEREDIA',2)
Insert into Distrito values (2, 4,'Heredia',2)
Insert into Distrito values (2, 4,'Mercedes',2)
Insert into Distrito values (2, 4,'San Francisco',2)
Insert into Distrito values (2, 4,'Ulloa',2)
Insert into Distrito values (2, 4,'Vara Blanca',2)
Insert into Canton values (2,' SANTO DOMINGO',2)
Insert into Distrito values (2, 5,'Santo Domingo',2)
Insert into Distrito values (2, 5,'San Vicente',2)
Insert into Distrito values (2, 5,'San Miguel',2)
Insert into Distrito values (2, 5,'Paracito',2)
Insert into Distrito values (2, 5,'Santo Tomás',2)
Insert into Distrito values (2, 5,'Santa Rosa',2)
Insert into Distrito values (2, 5,'Tures',2)
Insert into Distrito values (2, 5,'Pará',2)
Insert into Canton values (2,' SAN RAFAEL',2)
Insert into Distrito values (2, 6, 'San Rafael',2)
Insert into Distrito values (2, 6, 'San Josecito',2)
Insert into Distrito values (2, 6, 'Santiago',2)
Insert into Distrito values (2, 6, 'Angeles',2)
Insert into Distrito values (2, 6, 'Concepción',2)

Insert into Provincia values('CARTAGO', 1,2);
Insert into Canton values (3,' CARTAGO',2)
Insert into Distrito values (3, 7,'Oriental',2)
Insert into Distrito values (3, 7,'Occidental',2)
Insert into Distrito values (3, 7,'Carmen',2)
Insert into Distrito values (3, 7,'San Nicolás',2)
Insert into Distrito values (3, 7,'Aguacaliente  (San Francisco)',2)
Insert into Distrito values (3, 7,'Guadalupe  (Arenilla)',2)
Insert into Distrito values (3, 7,'Corralillo',2)
Insert into Distrito values (3, 7,'Tierra Blanca',2)
Insert into Distrito values (3, 7,'Dulce Nombre',2)
Insert into Distrito values (3, 7,'Llano Grande',2)
Insert into Distrito values (3, 7,'Quebradilla',2)
Insert into Canton values (3,' PARAISO',2)
Insert into Distrito values (3, 8, 'Paraíso',2)
Insert into Distrito values (3, 8, 'Santiago',2)
Insert into Distrito values (3, 8, 'Orosi',2)
Insert into Distrito values (3, 8, 'Cachí',2)
Insert into Distrito values (3, 8, 'Llanos de Sta Lucia',2)
Insert into Canton values (3, ' LA UNION',2)
Insert into Distrito values (3, 9, 'Tres Ríos',2)
Insert into Distrito values (3, 9, 'San Diego',2)
Insert into Distrito values (3, 9, 'San Juan',2)
Insert into Distrito values (3, 9, 'San Rafael',2)
Insert into Distrito values (3, 9, 'Concepción',2)
Insert into Distrito values (3, 9, 'Dulce Nombre',2)
Insert into Distrito values (3, 9, 'San Ramón',2)
Insert into Distrito values (3, 9, 'Río Azul',2)


Insert into Provincia values('ALAJUELA', 1,2);
Insert into Canton values (4,' ALAJUELA',2)
Insert into Distrito values (4, 10,'Alajuela',2)
Insert into Distrito values (4, 10,'San José',2)
Insert into Distrito values (4, 10,'Carrizal',2)
Insert into Distrito values (4, 10,'San Antonio',2)
Insert into Distrito values (4, 10,'Guácima',2)
Insert into Distrito values (4, 10,'San Isidro',2)
Insert into Distrito values (4, 10,'Sabanilla',2)
Insert into Distrito values (4, 10,'San Rafael',2)
Insert into Distrito values (4, 10,'Río Segundo',2)
Insert into Distrito values (4, 10,'Desamparados',2)
Insert into Distrito values (4, 10,'Turrucares',2)
Insert into Distrito values (4, 10,'Tambor',2)
Insert into Distrito values (4, 10,'La Garita',2)
Insert into Distrito values (4, 10,'Sarapiquí',2)
Insert into Canton values (4,' SAN RAMON',2)
Insert into Distrito values (4, 11,'San Ramón',2)
Insert into Distrito values (4, 11,'Santiago',2)
Insert into Distrito values (4, 11,'San Juan',2)
Insert into Distrito values (4, 11,'Piedades Norte',2)
Insert into Distrito values (4, 11,'Piedades Sur',2)
Insert into Distrito values (4, 11,'San Rafael')
Insert into Distrito values (4, 11,'San Isidro')
Insert into Distrito values (4, 11,'Angeles')
Insert into Distrito values (4, 11,'Alfaro')
Insert into Distrito values (4, 11,'Volio')
Insert into Distrito values (4, 11,'Concepción')
Insert into Distrito values (4, 11,'Zapotal')
Insert into Distrito values (4, 11,'San Isidro de Peñas Blancas')
Insert into Distrito values (4, 11,'San Lorenzo')
Insert into Canton values (4, '  GRECIA')
Insert into Distrito values (4, 12,'Grecia')
Insert into Distrito values (4, 12,'San Isidro')
Insert into Distrito values (4, 12,'San José')
Insert into Distrito values (4, 12,'San Roque')
Insert into Distrito values (4, 12,'Tacares')
Insert into Distrito values (4, 12,'Puente Piedra')
Insert into Distrito values (4, 12,'Bolívar')



Insert into Provincia values('LIMON', 1);
Insert into Canton values (5,' LIMON')
Insert into Distrito values (5, 13, 'Limón')
Insert into Distrito values (5, 13, 'Valle  La Estrella')
Insert into Distrito values (5, 13, 'Río Blanco')
Insert into Distrito values (5, 13, 'Matama')
Insert into Canton values (5, ' POCOCI')
Insert into Distrito values (5, 14, 'Guápiles')
Insert into Distrito values (5, 14,'Jiménez')
Insert into Distrito values (5, 14,'Rita')
Insert into Distrito values (5, 14,'Roxana')
Insert into Distrito values (5, 14,'Cariari')
Insert into Distrito values (5, 14,'Colorado')
Insert into Distrito values (5, 14,'La Colonia')
Insert into Canton values (5,' SIQUIRRES')
Insert into Distrito values (5, 15,'Siquirres')
Insert into Distrito values (5, 15,'Pacuarito')
Insert into Distrito values (5, 15,'Florida')
Insert into Distrito values (5, 15,'Germania')
Insert into Distrito values (5, 15,'Cairo')
Insert into Distrito values (5, 15,'Alegría')


Insert into Provincia values('GUANACASTE', 1);
Insert into Canton values (6, ' LIBERIA')
Insert into Distrito values (6, 16,'Liberia')
Insert into Distrito values (6, 16,'Cañas Dulces')
Insert into Distrito values (6, 16,'Mayorga')
Insert into Distrito values (6, 16,'Nacascolo')
Insert into Distrito values (6, 16,'Curubande')
Insert into Canton values (6, ' NICOYA')
Insert into Distrito values (6, 17,'Nicoya')
Insert into Distrito values (6, 17,'Mansión')
Insert into Distrito values (6, 17,'San Antonio')
Insert into Distrito values (6, 17,'Quebrada Honda')
Insert into Distrito values (6, 17,'Sámara')
Insert into Distrito values (6, 17,'Nosara')
Insert into Distrito values (6, 17,'Belén de Nosarita')
Insert into Canton values (6,' SANTA CRUZ')
Insert into Distrito values (6, 18,'Santa Cruz')
Insert into Distrito values (6, 18,'Bolsón')
Insert into Distrito values (6, 18,'Veintisiete de Abril')
Insert into Distrito values (6, 18,'Tempate')
Insert into Distrito values (6, 18,'Cartagena')
Insert into Distrito values (6, 18,'Cuajiniquil')
Insert into Distrito values (6, 18,'Diriá')
Insert into Distrito values (6, 18,'Cabo Velas')
Insert into Distrito values (6, 18,'Tamarindo')


Insert into Provincia values('PUNTARENAS', 1);
Insert into Canton values (7, ' PUNTARENAS')
Insert into Distrito values (7, 19,'Puntarenas')
Insert into Distrito values (7, 19,'Pitahaya')
Insert into Distrito values (7, 19,'Chomes')
Insert into Distrito values (7, 19,'Lepanto')
Insert into Distrito values (7, 19,'Paquera')
Insert into Distrito values (7, 19,'Manzanillo')
Insert into Distrito values (7, 19,'Guacimal')
Insert into Distrito values (7, 19,'Barranca')
Insert into Distrito values (7, 19,'Monte Verde')
Insert into Distrito values (7, 19,'Isla del Coco')
Insert into Distrito values (7, 19,'Cóbano')
Insert into Distrito values (7, 19,'Chacarita')
Insert into Distrito values (7, 19,'Chira (Isla)')
Insert into Distrito values (7, 19,'Acapulco')
Insert into Distrito values (7, 19,'El Roble')
Insert into Distrito values (7, 19,'Arancibia')
Insert into Canton values (7,' ESPARZA')
Insert into Distrito values (7, 20,'Espíritu Santo')
Insert into Distrito values (7, 20,'San Juan Grande')
Insert into Distrito values (7, 20,'Macacona')
Insert into Distrito values (7, 20,'San Rafael')
Insert into Distrito values (7, 20,'San Jerónimo')
Insert into Distrito values (7, 20,'Caldera')
Insert into Canton values (7,' BUENOS AIRES')
Insert into Distrito values (7, 21,'Buenos Aires')
Insert into Distrito values (7, 21,'Volcán')
Insert into Distrito values (7, 21,'Potrero Grande')
Insert into Distrito values (7, 21,'Boruca')
Insert into Distrito values (7, 21,'Pilas')
Insert into Distrito values (7, 21,'Colinas o Bajo de Maíz')
Insert into Distrito values (7, 21,'Chánguena')
Insert into Distrito values (7, 21,'Biolley')
Insert into Distrito values (7, 21,'Brunka')